bunch of improvements; add grappling hook
bigratenthusiast/crypt pull request #4
Opened 2021-03-29 04:55 UTC by sourTaste000

- added countdown for death match
- changed `sendMessages` to `sendTitle`
- fixed `spreadplayers` (again)
- removed redundant quotes in utils
- added Grappling Hook

2021-03-29 15:45 UTC, humboldt123 requested changes

2021-03-29 15:45 UTC, humboldt123 commented on src/main/java/me/bigratenthusiast/crypt/Main.kt
> +                    Thread.sleep(1000)
Instead of using `Thread.Sleep`, schedule an event. (Same applies for everywhere you use `Thread.Sleep`)

2021-03-29 15:45 UTC, humboldt123 commented on src/main/java/me/bigratenthusiast/crypt/Main.kt
> +            Thread.sleep((45 * 1000))
Please schedule an event and make this value a variable instead of hard-coding it.

2021-03-29 15:58 UTC, bigratenthusiast requested changes

2021-03-29 15:58 UTC, bigratenthusiast commented on src/main/java/me/bigratenthusiast/crypt/Main.kt
> +                    Thread.sleep(1000)
Please schedule an event instead of using `Thread.sleep()` wherever it is used

2021-03-29 15:58 UTC, bigratenthusiast commented on src/main/java/me/bigratenthusiast/crypt/Main.kt
> +            Thread.sleep((45 * 1000))
Schedule an event and also make this value a variable rather than hard-coding it in.

2021-03-29 23:13 UTC, bigratenthusiast commented
What a wonderful commit name.

2021-03-31 14:48 UTC, bigratenthusiast approved these changes

2021-03-31 18:18 UTC, merged